my:
   greeting: Seventh time updated Hello world From config server application file in github.com
   list:
       values: One, Two, Three, Four

db:
   connection: test connection string here from config server
   host: 127.0.0.1
   port: 1200
